name: Build and Push to ACR

on:
  push:
    branches:
      - '**' # Adjust this as needed

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/all-builds/paper:${{ github.sha }}

      # Optional: Deploy to Azure Web App for Containers or any other Azure service here
      # - name: Deploy to Azure
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: <Your-App-Name>
      #     slot-name: <Your-Slot-Name> # Optional
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     images: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/myapp:${{ github.sha }}
